# Generated by Django 4.0.6 on 2022-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
