# Generated by Django 4.0.6 on 2022-08-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0002_to_do_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do',
            name='category',
        ),
        migrations.RemoveField(
            model_name='to_do',
            name='deadline',
        ),
    ]
