# Generated by Django 4.0.6 on 2022-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0003_remove_to_do_category_remove_to_do_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
