# Generated by Django 4.0.6 on 2022-09-20 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0004_to_do_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 20, 15, 20, 47, 364302)),
        ),
    ]
